#!/usr/bin/env node
/*
 * Triggers - Plugin for Obsidian
 * Copyright (c) 2026 Ruben Khachaturov
 * SPDX-License-Identifier: MIT
 *
 * Writes docs/reference.md from the registries the plugin itself reads, so the
 * names and descriptions a user sees cannot drift from the ones written down.
 *
 * The registries are imported, not parsed: `src/types/registry.ts` and the
 * English dictionary import nothing from `obsidian`, so Node runs them as they
 * are. That is the whole reason those two files are kept free of it.
 *
 * Prose lives in docs/templates/reference.md and is never overwritten: the
 * generator only fills its placeholders.
 *
 *   --check   exit non-zero when the file on disk is not what would be written
 */

import { promises as fs } from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';
import { STRINGS_EN } from '../src/i18n/locales/en.ts';
import { FIELDS, OPERATORS, VARIABLES } from '../src/types/registry.ts';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const target = path.join(root, 'docs', 'reference.md');
const templatePath = path.join(root, 'docs', 'templates', 'reference.md');

const WARNING = '<!-- Generated by scripts/generate-docs.mjs. Edit docs/templates/reference.md. -->';

/** Resolve `when.matchPath` against the English dictionary. */
function english(dotted) {
  let value = STRINGS_EN;
  for (const part of dotted.split('.')) value = value?.[part];

  if (typeof value !== 'string') throw new Error(`a registry names "${dotted}", which en.ts does not have`);
  return value;
}

function operatorLabel(op) {
  const spec = OPERATORS.find((entry) => entry.op === op);
  if (spec === undefined) throw new Error(`a field offers "${op}", which no operator declares`);
  return spec.label;
}

function table(header, rows) {
  const separator = header.map(() => '---');
  return [header, separator, ...rows].map((cells) => `| ${cells.join(' | ')} |`).join('\n');
}

async function build() {
  const fields = table(
    ['Field', 'Shown in', 'Operators', 'Example value'],
    FIELDS.map((field) => [
      `**${english(field.label)}**`,
      field.views === undefined ? 'every view' : field.views.map((view) => `\`${view}\``).join(', '),
      field.ops.map((op) => `**${english(operatorLabel(op))}**`).join(', '),
      `\`${english(field.hint)}\``,
    ]),
  );

  const operators = table(
    ['Operator', 'Holds when'],
    OPERATORS.map((operator) => [`**${english(operator.label)}**`, operator.holds]),
  );

  const variables = table(
    ['Variable', 'Value'],
    VARIABLES.map((variable) => [`\`${variable.name}\``, variable.holds]),
  );

  const template = await fs.readFile(templatePath, 'utf8');
  const filled = template
    .replace('{{FIELDS}}', fields)
    .replace('{{OPERATORS}}', operators)
    .replace('{{VARIABLES}}', variables);
  return `${WARNING}\n\n${filled.trimEnd()}\n`;
}

async function main() {
  const wanted = await build();

  if (!process.argv.includes('--check')) {
    await fs.writeFile(target, wanted);
    console.log(`Wrote ${path.relative(root, target)}`);
    return;
  }

  const current = await fs.readFile(target, 'utf8').catch(() => '');
  if (current === wanted) {
    console.log('docs/reference.md is current.');
    return;
  }

  console.error('docs/reference.md is stale. Run `mise run docs`.');
  process.exit(1);
}

await main();
